
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_head
    pid: {p: 2.0, i: 0.0, d: 0.0}






